
slider:
  - url: ./user/themes/sinoclean/images/homepage_cycle/sinoclean1.jpg
    id: slide1
  - url: ./user/themes/sinoclean/images/homepage_cycle/sinoclean2.jpg
    id: slide2
  - url: ./user/themes/sinoclean/images/homepage_cycle/sinoclean3.jpg
    id: slide3
  - url: ./user/themes/sinoclean/images/homepage_cycle/sinoclean4.jpg
    id: slide4
  - url: ./user/themes/sinoclean/images/homepage_cycle/sinocleanmob1.jpg
    id: slidem1
  - url: ./user/themes/sinoclean/images/homepage_cycle/sinocleanmob2.jpg
    id: slidem2
  - url: ./user/themes/sinoclean/images/homepage_cycle/sinocleanmob3.jpg
    id: slidem3
  - url: ./user/themes/sinoclean/images/homepage_cycle/sinocleanmob4.jpg
    id: slidem4

# Button Links
link1:
  en: Engineering
  zh: 工程领域
  url: ./engineering
  url_zh: ../zh/engineering
link2:
  en: Company
  zh: 公司简介
  url: ./about
  url_zh: ../zh/about
link3:
  en: Contact Us
  zh: 联系我们
  url: ./contact
  url_zh: ../zh/contact

# Engineering links
enginlinks:
  - en: Electrical
    zh: 电子工程
    url: ./engineering/electrical
    url_zh: ../zh/engineering/electrical
  - en: Optical Fiber Cable Projects
    zh: 光纤光缆工程
    url: ./engineering/optical
    url_zh: ../zh/engineering/optical
  - en: Biomedical
    zh: 生物医药食品工程
    url: ./engineering/biomed
    url_zh: ../zh/engineering/biomed
  - en: Photovoltaic Cell
    zh: 光伏太阳能工程
    url: ./engineering/pvc
    url_zh: ../zh/engineering/pvc
  - en: Automotive
    zh: 汽车制造业项目
    url: ./engineering/auto
    url_zh: ../zh/engineering/auto
  - en: Public Utility
    zh: 公共事业工程
    url: ./engineering/pu
    url_zh: ../zh/engineering/pu


# Photo Captions
header1:
  en: 13 billion yuan revenue since founding
  zh: 成立以来，完成130多亿业绩
  img: ./user/themes/sinoclean/images/office/office1.png
header2:
  en: No. 1 in the Optical Fiber Cable industry
  zh: 光纤光缆工程行业第一
  img: ./user/themes/sinoclean/images/office/office3.png



# Map
location: Xi'an+International+Conference+Center+Qujiang+Hotel
