title: Sinoclean
author:
  name: Kevin Qi
  email: 'kevinqi34@gmail.com'
metadata:
    description: 'Sinoclean is an engineering specialized in clean technologies.'



#Top Menu
top_menu:
  img_url: /images/site_logo.jpg
  menu_items:
    - name: Contact Us
      name_zh: 联系我们
      url: /contact
      url_zh: /contact
    - name: Jobs
      name_zh: 人力资源
      url: /jobs
      url_zh: /jobs
    - name: News
      name_zh: 新闻中心
      url: /news
      url_zh: /news
    - name: Engineering
      name_zh: 工程领域
      url: /engineering
      url_zh: /engineering
    - name: Licenses & Awards
      name_zh: 资质和荣誉
      url: /licenses
      url_zh: /licenses
    - name: About Us
      name_zh: 公司概况
      url: /about
      url_zh: /about


mob_menu:
  button: /images/menu.png



#Footer
footer_txt: Copyright © 2016 Sinoclean Construction & Engineering Group All Rights Reserved
footer_txt_zh: Copyright © 2016 中洁建工集团（中洁集团） All Rights Reserved
